all:
	javac *.java packages/*.java
knn:
	javac knn.java packages/*.java
regression:
	javac regression.java packages/*.java
nn_regression:
	javac nn_regression.java packages/*.java
clean:
	rm *.class
	rm packages/*.class
